"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import Website, WebsiteCreate, WebsiteUpdate
from .store import store

app = FastAPI(
    title="Tutorial Interactive Chip Simulation and Education website API",
    version="0.1.0",
    description="REST API for Tutorial Interactive Chip Simulation and Education website. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "websites", "description": "Websites managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/websites", response_model=List[Website], tags=["websites"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/websites", response_model=Website, status_code=201, tags=["websites"])
def create_item(body: WebsiteCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/websites/{item_id}", response_model=Website, tags=["websites"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Website not found")
    return item


@app.patch("/api/websites/{item_id}", response_model=Website, tags=["websites"])
def update_item(item_id: int, body: WebsiteUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Website not found")
    return item


@app.delete("/api/websites/{item_id}", status_code=204, tags=["websites"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Website not found")
